/**
 * Lentera Pasar - Data Master Katalog 73 Template Website UMKM
 * Format data terstruktur untuk katalog showcase ala marketplace / Goomsite
 */

const BIDANG_INFO = {
  "01-fnb-kuliner": {
    "id": "01-fnb-kuliner",
    "no": "01",
    "name": "Kuliner & F&B",
    "fullName": "F&B / Kuliner & Restoran",
    "icon": "utensils",
    "color": "amber",
    "badgeClass": "bg-amber-100 text-amber-800 border-amber-200",
    "themeGradient": "from-amber-500 to-orange-500",
    "description": "Solusi website kuliner modern mulai dari ricebowl, coffee shop, katering higienis, frozen food hingga kuliner tradisional dengan pemesanan langsung ke WhatsApp dapur Anda."
  },
  "02-fashion-skincare": {
    "id": "02-fashion-skincare",
    "no": "02",
    "name": "Fashion & Beauty",
    "fullName": "Fashion, Beauty & Skincare",
    "icon": "sparkle",
    "color": "pink",
    "badgeClass": "bg-pink-100 text-pink-800 border-pink-200",
    "themeGradient": "from-pink-500 to-rose-500",
    "description": "Etalase visual mewah untuk modest fashion, brand streetwear, klinik kecantikan & skincare, parfum artisan, dan perhiasan berkelas."
  },
  "03-ritel-gadget-hobi": {
    "id": "03-ritel-gadget-hobi",
    "no": "03",
    "name": "Ritel & Hobi",
    "fullName": "Ritel, Gadget & Hobi",
    "icon": "gamepad-2",
    "color": "indigo",
    "badgeClass": "bg-indigo-100 text-indigo-800 border-indigo-200",
    "themeGradient": "from-indigo-500 to-blue-600",
    "description": "Toko online dinamis untuk gadget smartphone, gaming peripheral, perlengkapan outdoor, hobi diecast, dan kebutuhan harian."
  },
  "04-kriya-dekorasi": {
    "id": "04-kriya-dekorasi",
    "no": "04",
    "name": "Kriya & Dekorasi",
    "fullName": "Kriya, Furnitur & Dekorasi",
    "icon": "gem",
    "color": "emerald",
    "badgeClass": "bg-emerald-100 text-emerald-800 border-emerald-200",
    "themeGradient": "from-emerald-600 to-teal-700",
    "description": "Galeri karya furnitur kayu solid, seni keramik tembikar, batik heritage, lilin aromaterapi, dan dekorasi estetik rumah."
  },
  "05-agrobisnis-bahan-mentah": {
    "id": "05-agrobisnis-bahan-mentah",
    "no": "05",
    "name": "Agrobisnis & Alam",
    "fullName": "Agrobisnis & Hasil Alam",
    "icon": "sprout",
    "color": "lime",
    "badgeClass": "bg-lime-100 text-lime-800 border-lime-200",
    "themeGradient": "from-lime-600 to-green-700",
    "description": "Etalase komoditas sayur hidroponik, beras organik, hasil laut segar, bibit tanaman unggul, dan madu hutan murni nusantara."
  },
  "06-supplier-grosir-b2b": {
    "id": "06-supplier-grosir-b2b",
    "no": "06",
    "name": "Supplier & B2B",
    "fullName": "Supplier, Grosir & B2B",
    "icon": "factory",
    "color": "slate",
    "badgeClass": "bg-slate-200 text-slate-800 border-slate-300",
    "themeGradient": "from-slate-700 to-slate-900",
    "description": "Portal profesional pabrik kemasan box & pouch, konveksi seragam, distributor sembako, dan supplier bahan baku industri skala besar."
  }
};

const TEMPLATES_DATA = [
  {
    "id": "fnb-ricebowl-pop",
    "title": "Ricebowl Pop",
    "niche": "Kuliner Praktis",
    "bidang": "01-fnb-kuliner",
    "group": "Group A",
    "folder": "fnb-ricebowl-pop",
    "demoUrl": "./01-fnb-kuliner/fnb-ricebowl-pop/index.html",
    "description": "Visual ceria energik, fitur promo paket kombo hemat, dan navigasi pemesanan kilat langsung ke chat WhatsApp.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "ricebowl fnb makanan kuliner ayam saus pop modern santap",
    "badgeFeatures": []
  },
  {
    "id": "fnb-frozen-clean",
    "title": "Frozen Clean Hub",
    "niche": "Olahan Beku Higienis",
    "bidang": "01-fnb-kuliner",
    "group": "Group A",
    "folder": "fnb-frozen-clean",
    "demoUrl": "./01-fnb-kuliner/fnb-frozen-clean/index.html",
    "description": "Katalog suhu beku terstruktur, panduan simpan higienis, dan formulir paket kemitraan reseller otomatis.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "frozen food kuliner olahan beku higienis reseller nugget dimsum",
    "badgeFeatures": []
  },
  {
    "id": "fnb-snack-crunchy",
    "title": "Snack Crunchy Vault",
    "niche": "Camilan Renyah",
    "bidang": "01-fnb-kuliner",
    "group": "Group A",
    "folder": "fnb-snack-crunchy",
    "demoUrl": "./01-fnb-kuliner/fnb-snack-crunchy/index.html",
    "description": "Desain energik berkarakter, etalase pilihan tingkat kepedasan, dan sistem bundle kado oleh-oleh.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "snack crunchy camilan keripik renyah oleh-oleh gurih",
    "badgeFeatures": []
  },
  {
    "id": "fnb-sambal-nusantara",
    "title": "Sambal Nusantara",
    "niche": "Kekayaan Nusantara",
    "bidang": "01-fnb-kuliner",
    "group": "Group A",
    "folder": "fnb-sambal-nusantara",
    "demoUrl": "./01-fnb-kuliner/fnb-sambal-nusantara/index.html",
    "description": "Sentuhan estetika tradisional hangat, kisah racikan rempah nusantara, dan form order botol satuan / lusinan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "sambal nusantara bumbu dapur khas cabai botolan pedas",
    "badgeFeatures": []
  },
  {
    "id": "fnb-coffee-dark",
    "title": "Artisan Coffee Dark",
    "niche": "Specialty Roastery",
    "bidang": "01-fnb-kuliner",
    "group": "Group B",
    "folder": "fnb-coffee-dark",
    "demoUrl": "./01-fnb-kuliner/fnb-coffee-dark/index.html",
    "description": "Dark mode elegan mewah, kartu profil tasting notes biji kopi, dan direct booking meja / beli beans via WhatsApp.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "coffee dark artisan roastery cafe biji kopi espresso",
    "badgeFeatures": []
  },
  {
    "id": "fnb-catering-clean",
    "title": "Catering Clean Studio",
    "niche": "Katering & Acara",
    "bidang": "01-fnb-kuliner",
    "group": "Group B",
    "folder": "fnb-catering-clean",
    "demoUrl": "./01-fnb-kuliner/fnb-catering-clean/index.html",
    "description": "Struktur tabel menu mingguan teratur, kalkulator porsi hajatan, dan form konsultasi prasmanan otomatis.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "catering clean meal plan harian kantor wedding prasmanan",
    "badgeFeatures": []
  },
  {
    "id": "fnb-dessert-pastel",
    "title": "Dessert Pastel Haven",
    "niche": "Sweet & Delight",
    "bidang": "01-fnb-kuliner",
    "group": "Group B",
    "folder": "fnb-dessert-pastel",
    "demoUrl": "./01-fnb-kuliner/fnb-dessert-pastel/index.html",
    "description": "Palet warna pastel manis menggugah selera, showcase dessert box fotogenik, dan sistem PO tanggal pengiriman.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "dessert pastel manis pudding dessert box cake pastry",
    "badgeFeatures": []
  },
  {
    "id": "fnb-meat-butcher",
    "title": "Butcher & Meat Shop",
    "niche": "Premium Cuts",
    "bidang": "01-fnb-kuliner",
    "group": "Group B",
    "folder": "fnb-meat-butcher",
    "demoUrl": "./01-fnb-kuliner/fnb-meat-butcher/index.html",
    "description": "Layout maskulin premium, edukasi potongan daging & marbling score wagyu, dan kalkulasi gramatur pesanan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "meat butcher daging wagyu steak sapi potong halal",
    "badgeFeatures": []
  },
  {
    "id": "fnb-bakery-artisan",
    "title": "Bakery Artisan",
    "niche": "Oven Fresh Daily",
    "bidang": "01-fnb-kuliner",
    "group": "Group C",
    "folder": "fnb-bakery-artisan",
    "demoUrl": "./01-fnb-kuliner/fnb-bakery-artisan/index.html",
    "description": "Earthy warm tone, cerita fermentasi alami sourdough, dan jam panggang harian untuk kepastian kesegaran roti.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "bakery artisan roti sourdough croissant fresh oven pastry",
    "badgeFeatures": []
  },
  {
    "id": "fnb-cake-celebration",
    "title": "Cake Celebration",
    "niche": "Kue Ulang Tahun & Acara",
    "bidang": "01-fnb-kuliner",
    "group": "Group C",
    "folder": "fnb-cake-celebration",
    "demoUrl": "./01-fnb-kuliner/fnb-cake-celebration/index.html",
    "description": "Galeri pesanan custom interaktif, opsi diameter kue, pilihan ucapan topper, dan kalkulasi slot tanggal pesta.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "cake celebration kue ulang tahun tart custom wedding pesta",
    "badgeFeatures": []
  },
  {
    "id": "fnb-healthy-diet",
    "title": "Healthy Diet & Salad",
    "niche": "Nutrisi Seimbang",
    "bidang": "01-fnb-kuliner",
    "group": "Group C",
    "folder": "fnb-healthy-diet",
    "demoUrl": "./01-fnb-kuliner/fnb-healthy-diet/index.html",
    "description": "Fresh green vibes, tabel rincian kalori & makronutrisi lengkap, serta alur pendaftaran langganan catering sehat.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "healthy diet salad vegan organik makanan sehat kalori gym",
    "badgeFeatures": []
  },
  {
    "id": "fnb-tradisional-tampah",
    "title": "Tradisional Tampah",
    "niche": "Kearifan Kuliner Lokal",
    "bidang": "01-fnb-kuliner",
    "group": "Group C",
    "folder": "fnb-tradisional-tampah",
    "demoUrl": "./01-fnb-kuliner/fnb-tradisional-tampah/index.html",
    "description": "Nuansa kearifan lokal berkelas, paket tampah jajan pasar untuk rapat, dan pesanan nasi tumpeng syukuran.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "tradisional tampah kue basah jajan pasar nasi tumpeng selamatan",
    "badgeFeatures": []
  },
  {
    "id": "fashion-casual-minimal",
    "title": "Casual Minimal",
    "niche": "Casual Minimal",
    "bidang": "02-fashion-skincare",
    "group": "Group A",
    "folder": "fashion-casual-minimal",
    "demoUrl": "./02-fashion-skincare/fashion-casual-minimal/index.html",
    "description": "",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fashion casual minimal apparel baju kemeja celana lookbook",
    "badgeFeatures": []
  },
  {
    "id": "fashion-modest-editorial",
    "title": "Modest Editorial",
    "niche": "Modest Editorial",
    "bidang": "02-fashion-skincare",
    "group": "Group A",
    "folder": "fashion-modest-editorial",
    "demoUrl": "./02-fashion-skincare/fashion-modest-editorial/index.html",
    "description": "",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fashion modest hijab editorial gamis muslimah anggun syari",
    "badgeFeatures": []
  },
  {
    "id": "fashion-kids-pastel",
    "title": "Kids Pastel",
    "niche": "Kids Pastel",
    "bidang": "02-fashion-skincare",
    "group": "Group A",
    "folder": "fashion-kids-pastel",
    "demoUrl": "./02-fashion-skincare/fashion-kids-pastel/index.html",
    "description": "",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fashion kids pastel baju anak bayi balita katun lembut",
    "badgeFeatures": []
  },
  {
    "id": "fashion-activewear-kinetic",
    "title": "Activewear Kinetic",
    "niche": "Activewear Kinetic",
    "bidang": "02-fashion-skincare",
    "group": "Group A",
    "folder": "fashion-activewear-kinetic",
    "demoUrl": "./02-fashion-skincare/fashion-activewear-kinetic/index.html",
    "description": "",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fashion activewear olahraga gym sport lari kinetic legging",
    "badgeFeatures": []
  },
  {
    "id": "fashion-loungewear-cozy",
    "title": "Loungewear Cozy",
    "niche": "Loungewear Cozy",
    "bidang": "02-fashion-skincare",
    "group": "Group A",
    "folder": "fashion-loungewear-cozy",
    "demoUrl": "./02-fashion-skincare/fashion-loungewear-cozy/index.html",
    "description": "",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fashion loungewear piyama daster tidur santai rumah cozy",
    "badgeFeatures": []
  },
  {
    "id": "skincare-clinical-lab",
    "title": "Clinical Lab Skincare",
    "niche": "Clinical Lab Skincare",
    "bidang": "02-fashion-skincare",
    "group": "Group B",
    "folder": "skincare-clinical-lab",
    "demoUrl": "./02-fashion-skincare/skincare-clinical-lab/index.html",
    "description": "Desain klinis terpercaya, edukasi kandungan bahan aktif serum & konsultasi masalah kulit ke WhatsApp.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "skincare clinical lab dokter kulit serum jerawat glowing klinik",
    "badgeFeatures": []
  },
  {
    "id": "makeup-glam-studio",
    "title": "Makeup Glam Studio",
    "niche": "Makeup Glam Studio",
    "bidang": "02-fashion-skincare",
    "group": "Group B",
    "folder": "makeup-glam-studio",
    "demoUrl": "./02-fashion-skincare/makeup-glam-studio/index.html",
    "description": "Shade picker interaktif, katalog kosmetik glamor, & video swatch bibir yang memikat calon pembeli.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "makeup glam studio kosmetik lipstik foundation beauty kosmetik",
    "badgeFeatures": []
  },
  {
    "id": "perfume-luxury-atelier",
    "title": "Perfume Luxury Atelier",
    "niche": "Perfume Luxury Atelier",
    "bidang": "02-fashion-skincare",
    "group": "Group B",
    "folder": "perfume-luxury-atelier",
    "demoUrl": "./02-fashion-skincare/perfume-luxury-atelier/index.html",
    "description": "Atmosfer kemewahan wangi, piramida notes aroma (top, heart, base) & kurasi decant tester kit.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "perfume luxury atelier parfum wewangian aroma extrait notes",
    "badgeFeatures": []
  },
  {
    "id": "bodycare-botanical-spa",
    "title": "Botanical Spa Bodycare",
    "niche": "Botanical Spa Bodycare",
    "bidang": "02-fashion-skincare",
    "group": "Group B",
    "folder": "bodycare-botanical-spa",
    "demoUrl": "./02-fashion-skincare/bodycare-botanical-spa/index.html",
    "description": "Nuansa relaksasi alami menenangkan, formulasi herbal organik & paket perawatan tubuh spa di rumah.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "bodycare botanical spa lulur sabun scrub minyak esensial herbal",
    "badgeFeatures": []
  },
  {
    "id": "footwear-sneakers-street",
    "title": "Sneakers Street",
    "niche": "Sneakers Street",
    "bidang": "02-fashion-skincare",
    "group": "Group C",
    "folder": "footwear-sneakers-street",
    "demoUrl": "./02-fashion-skincare/footwear-sneakers-street/index.html",
    "description": "Gaya jalanan maskulin edgy, showcase drop rilis terbatas, & panduan ukuran sol kaki presisi.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "footwear sneakers sepatu street kasual drop sol streetwear",
    "badgeFeatures": []
  },
  {
    "id": "bags-leather-atelier",
    "title": "Leather Bags Atelier",
    "niche": "Leather Bags Atelier",
    "bidang": "02-fashion-skincare",
    "group": "Group C",
    "folder": "bags-leather-atelier",
    "demoUrl": "./02-fashion-skincare/bags-leather-atelier/index.html",
    "description": "Sentuhan artisan kulit sapi asli, showcase kekuatan jahitan, serta kompartemen tas fungsional.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "bags leather tas kulit ransel jahit tangan dompet totebag",
    "badgeFeatures": []
  },
  {
    "id": "accessories-modern-optics",
    "title": "Modern Optics Eyewear",
    "niche": "Modern Optics Eyewear",
    "bidang": "02-fashion-skincare",
    "group": "Group C",
    "folder": "accessories-modern-optics",
    "demoUrl": "./02-fashion-skincare/accessories-modern-optics/index.html",
    "description": "Koleksi frame kacamata kekinian, panduan bentuk wajah, & form pemesanan resep lensa kustom.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "accessories modern optics kacamata frame lensa optik sunglasses",
    "badgeFeatures": []
  },
  {
    "id": "jewelry-timepiece-luxury",
    "title": "Jewelry & Timepiece",
    "niche": "Jewelry & Timepiece",
    "bidang": "02-fashion-skincare",
    "group": "Group C",
    "folder": "jewelry-timepiece-luxury",
    "demoUrl": "./02-fashion-skincare/jewelry-timepiece-luxury/index.html",
    "description": "Tampilan eksklusif berkilau, sertifikat keaslian karat emas, & layanan konsultasi custom cincin nikah.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "jewelry timepiece jam tangan perhiasan cincin emas berlian kalung",
    "badgeFeatures": []
  },
  {
    "id": "gadget-mobile-tech",
    "title": "Mobile Tech Gadget",
    "niche": "Mobile Tech Gadget",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group A",
    "folder": "gadget-mobile-tech",
    "demoUrl": "./03-ritel-gadget-hobi/gadget-mobile-tech/index.html",
    "description": "Layout komparasi spesifikasi chipset & kamera, status garansi resmi, serta paket aksesoris bundling.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "gadget mobile tech smartphone hp android ios tablet garansi",
    "badgeFeatures": []
  },
  {
    "id": "gaming-peripherals-studio",
    "title": "Gaming Peripherals Studio",
    "niche": "Gaming Peripherals Studio",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group A",
    "folder": "gaming-peripherals-studio",
    "demoUrl": "./03-ritel-gadget-hobi/gaming-peripherals-studio/index.html",
    "description": "Cyberpunk dark aesthetic, rincian switch mechanical keyboard, & polling rate mouse esports.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "gaming peripherals keyboard mouse rgb headset switch esport",
    "badgeFeatures": []
  },
  {
    "id": "tools-hardware-pro",
    "title": "Tools & Hardware Pro",
    "niche": "Tools & Hardware Pro",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group A",
    "folder": "tools-hardware-pro",
    "demoUrl": "./03-ritel-gadget-hobi/tools-hardware-pro/index.html",
    "description": "Tangguh industrial, spesifikasi torsi bor & voltase baterai, serta ketersediaan suku cadang servis.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "tools hardware bor perkakas pertukangan mesin teknik baut obeng",
    "badgeFeatures": []
  },
  {
    "id": "moto-garage-accessories",
    "title": "Moto Garage Accessories",
    "niche": "Moto Garage Accessories",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group A",
    "folder": "moto-garage-accessories",
    "demoUrl": "./03-ritel-gadget-hobi/moto-garage-accessories/index.html",
    "description": "Gaya bengkel modern bertenaga, filter kecocokan tipe motor & katalog helm/part touring.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "moto garage motor helm aksesoris knalpot bengkel touring",
    "badgeFeatures": []
  },
  {
    "id": "outdoor-camping-expedition",
    "title": "Outdoor Camping Expedition",
    "niche": "Outdoor Camping Expedition",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group B",
    "folder": "outdoor-camping-expedition",
    "demoUrl": "./03-ritel-gadget-hobi/outdoor-camping-expedition/index.html",
    "description": "Nuansa alam petualang tangguh, checklist peralatan mendaki, & persewaan/pembelian tenda via WA.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "outdoor camping gunung tenda carrier hiking ekspedisi alam",
    "badgeFeatures": []
  },
  {
    "id": "fitness-gym-gear",
    "title": "Fitness & Gym Gear",
    "niche": "Fitness & Gym Gear",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group B",
    "folder": "fitness-gym-gear",
    "demoUrl": "./03-ritel-gadget-hobi/fitness-gym-gear/index.html",
    "description": "Desain bersemangat tinggi, pilihan beban alat gym, serta panduan nutrisi suplemen pembentuk tubuh.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fitness gym gear dumbell suplemen whey protein latihan otot",
    "badgeFeatures": []
  },
  {
    "id": "hobby-collector-vault",
    "title": "Hobby Collector Vault",
    "niche": "Hobby Collector Vault",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group B",
    "folder": "hobby-collector-vault",
    "demoUrl": "./03-ritel-gadget-hobi/hobby-collector-vault/index.html",
    "description": "Etalase rilis edisi terbatas, grading kondisi kartu/figur, serta sistem PO slot rilis Jepang.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "hobby collector vault action figure gundam kartu tcg diecast",
    "badgeFeatures": []
  },
  {
    "id": "music-audio-studio",
    "title": "Music & Audio Studio",
    "niche": "Music & Audio Studio",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group B",
    "folder": "music-audio-studio",
    "demoUrl": "./03-ritel-gadget-hobi/music-audio-studio/index.html",
    "description": "Spesifikasi frekuensi audio Hi-Fi, instrumen musik akustik/elektrik, & konsultasi setup rekaman.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "music audio studio hifi gitar mic speaker sound rekaman",
    "badgeFeatures": []
  },
  {
    "id": "pet-care-haven",
    "title": "Pet Care Haven",
    "niche": "Pet Care Haven",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group C",
    "folder": "pet-care-haven",
    "demoUrl": "./03-ritel-gadget-hobi/pet-care-haven/index.html",
    "description": "Visual ramah hewan kesayangan, pemesanan pakan harian & booking jadwal grooming/vaksinasi.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "pet care haven kucing anjing pakan petshop grooming vaksin",
    "badgeFeatures": []
  },
  {
    "id": "plants-botanical-greenhouse",
    "title": "Botanical Greenhouse",
    "niche": "Botanical Greenhouse",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group C",
    "folder": "plants-botanical-greenhouse",
    "demoUrl": "./03-ritel-gadget-hobi/plants-botanical-greenhouse/index.html",
    "description": "Lush tropical green, indikator kebutuhan air & cahaya tiap varietas, serta pot terakota estetik.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "plants botanical greenhouse monstera aglaonema pot tanaman hias",
    "badgeFeatures": []
  },
  {
    "id": "stationery-aesthetic-desk",
    "title": "Stationery Desk Aesthetic",
    "niche": "Stationery Desk Aesthetic",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group C",
    "folder": "stationery-aesthetic-desk",
    "demoUrl": "./03-ritel-gadget-hobi/stationery-aesthetic-desk/index.html",
    "description": "Inspirasi journaling pastel, katalog pena kaligrafi, binder organizer, & perlengkapan meja produktif.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "stationery aesthetic desk buku jurnal pulpen binder stiker kantor",
    "badgeFeatures": []
  },
  {
    "id": "baby-montessori-play",
    "title": "Baby Montessori Play",
    "niche": "Baby Montessori Play",
    "bidang": "03-ritel-gadget-hobi",
    "group": "Group C",
    "folder": "baby-montessori-play",
    "demoUrl": "./03-ritel-gadget-hobi/baby-montessori-play/index.html",
    "description": "Mainan kayu non-toxic berstandar keamanan anak, panduan stimulasi motorik usia, & paket hadiah edukatif.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "baby montessori mainan kayu anak edukasi sensory play balita",
    "badgeFeatures": []
  },
  {
    "id": "furniture-teak-artisan",
    "title": "Teak Artisan Furniture",
    "niche": "Teak Artisan Furniture",
    "bidang": "04-kriya-dekorasi",
    "group": "Group A",
    "folder": "furniture-teak-artisan",
    "demoUrl": "./04-kriya-dekorasi/furniture-teak-artisan/index.html",
    "description": "Serat kayu jati solid elegan, garansi kekuatan lintas generasi, & custom ukuran pesanan interior.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "furniture teak artisan jati jepara kayu meja kursi interior",
    "badgeFeatures": []
  },
  {
    "id": "ceramics-clay-pottery",
    "title": "Clay & Ceramics Pottery",
    "niche": "Clay & Ceramics Pottery",
    "bidang": "04-kriya-dekorasi",
    "group": "Group A",
    "folder": "ceramics-clay-pottery",
    "demoUrl": "./04-kriya-dekorasi/ceramics-clay-pottery/index.html",
    "description": "Tekstur tanah liat alami buatan tangan, keunikan motif glasir tiap produk, & workshop tembikar.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "ceramics clay pottery keramik tembikar cangkir piring gerabah tanah liat",
    "badgeFeatures": []
  },
  {
    "id": "wall-decor-bohemian",
    "title": "Wall Decor Bohemian",
    "niche": "Wall Decor Bohemian",
    "bidang": "04-kriya-dekorasi",
    "group": "Group A",
    "folder": "wall-decor-bohemian",
    "demoUrl": "./04-kriya-dekorasi/wall-decor-bohemian/index.html",
    "description": "Makrame rajut & lukisan kanvas estetik, inspirasi tata ruang sudut estetik, serta paket instalasi dinding.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "wall decor bohemian makrame hiasan dinding kanvas lukisan cermin",
    "badgeFeatures": []
  },
  {
    "id": "home-textiles-cushion",
    "title": "Home Textiles Cushion",
    "niche": "Home Textiles Cushion",
    "bidang": "04-kriya-dekorasi",
    "group": "Group A",
    "folder": "home-textiles-cushion",
    "demoUrl": "./04-kriya-dekorasi/home-textiles-cushion/index.html",
    "description": "Kelembutan serat linen & rajut tenun, ragam motif bantal kursi sofa, serta custom sarung bantal.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "home textiles cushion bantal karpet selimut sarung bantal rajut",
    "badgeFeatures": []
  },
  {
    "id": "craft-natural-fiber",
    "title": "Natural Fiber Crafts",
    "niche": "Natural Fiber Crafts",
    "bidang": "04-kriya-dekorasi",
    "group": "Group B",
    "folder": "craft-natural-fiber",
    "demoUrl": "./04-kriya-dekorasi/craft-natural-fiber/index.html",
    "description": "Kearifan anyaman rotan & eceng gondok ramah lingkungan, keranjang serbaguna & kap lampu estetik.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "craft natural fiber rotan anyaman enceng gondok keranjang bambu",
    "badgeFeatures": []
  },
  {
    "id": "batik-heritage-atelier",
    "title": "Batik Heritage Atelier",
    "niche": "Batik Heritage Atelier",
    "bidang": "04-kriya-dekorasi",
    "group": "Group B",
    "folder": "batik-heritage-atelier",
    "demoUrl": "./04-kriya-dekorasi/batik-heritage-atelier/index.html",
    "description": "Filosofi mendalam tiap motif batik tulis & tenun leluhur, pewarna alami, & kain sutra eksklusif bernilai seni.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "batik heritage atelier batik tulis tenun sutra motif filosofi nusantara",
    "badgeFeatures": []
  },
  {
    "id": "craft-leather-workshop",
    "title": "Leather Craft Workshop",
    "niche": "Leather Craft Workshop",
    "bidang": "04-kriya-dekorasi",
    "group": "Group B",
    "folder": "craft-leather-workshop",
    "demoUrl": "./04-kriya-dekorasi/craft-leather-workshop/index.html",
    "description": "Karakter patina kulit sapi eksklusif, opsi personalisasi inisial nama grafir, & dompet buatan tangan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "craft leather workshop dompet kulit sabuk strap jam ukir nama custom",
    "badgeFeatures": []
  },
  {
    "id": "craft-carving-sculpture",
    "title": "Carving & Sculpture",
    "niche": "Carving & Sculpture",
    "bidang": "04-kriya-dekorasi",
    "group": "Group B",
    "folder": "craft-carving-sculpture",
    "demoUrl": "./04-kriya-dekorasi/craft-carving-sculpture/index.html",
    "description": "Detail pahatan kayu mahakarya maestro, relief dekoratif bernilai seni tinggi, & sertifikat karya asli.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "craft carving sculpture seni ukir patung kayu relief ornamen kriya",
    "badgeFeatures": []
  },
  {
    "id": "scent-candle-sanctuary",
    "title": "Scent Candle Sanctuary",
    "niche": "Scent Candle Sanctuary",
    "bidang": "04-kriya-dekorasi",
    "group": "Group C",
    "folder": "scent-candle-sanctuary",
    "demoUrl": "./04-kriya-dekorasi/scent-candle-sanctuary/index.html",
    "description": "Suasana relaksasi damai, 100% natural soy wax & essential oil, serta reed diffuser aromatik ruangan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "scent candle sanctuary lilin aromaterapi reed diffuser wangi relaksasi",
    "badgeFeatures": []
  },
  {
    "id": "floral-preserved-keepsake",
    "title": "Preserved Floral Keepsake",
    "niche": "Preserved Floral Keepsake",
    "bidang": "04-kriya-dekorasi",
    "group": "Group C",
    "folder": "floral-preserved-keepsake",
    "demoUrl": "./04-kriya-dekorasi/floral-preserved-keepsake/index.html",
    "description": "Keindahan bunga abadi tahan bertahun-tahun, buket mahar wisuda & bingkai pigura kenangan momen spesial.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "floral preserved keepsake bunga abadi wisuda buket mahar pernikahan kado",
    "badgeFeatures": []
  },
  {
    "id": "resin-terrazzo-studio",
    "title": "Resin & Terrazzo Studio",
    "niche": "Resin & Terrazzo Studio",
    "bidang": "04-kriya-dekorasi",
    "group": "Group C",
    "folder": "resin-terrazzo-studio",
    "demoUrl": "./04-kriya-dekorasi/resin-terrazzo-studio/index.html",
    "description": "Corak abstrak terrazzo modern, tatakan coaster cangkir resin mengkilap, & pernak-pernik dekorasi meja.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "resin terrazzo studio coaster tatakan cangkir nampan meja estetik seni",
    "badgeFeatures": []
  },
  {
    "id": "custom-hampers-curation",
    "title": "Custom Hampers Curation",
    "niche": "Custom Hampers Curation",
    "bidang": "04-kriya-dekorasi",
    "group": "Group C",
    "folder": "custom-hampers-curation",
    "demoUrl": "./04-kriya-dekorasi/custom-hampers-curation/index.html",
    "description": "Paket bingkisan kado perayaan mewah, personalisasi kartu ucapan, & kurasi souvenir corporate event.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "custom hampers curation kado hadiah lebaran natal imlek corporate gift",
    "badgeFeatures": []
  },
  {
    "id": "agro-hydroponic-fresh",
    "title": "Hydroponic Fresh Farm",
    "niche": "Hydroponic Fresh Farm",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group A",
    "folder": "agro-hydroponic-fresh",
    "demoUrl": "./05-agrobisnis-bahan-mentah/agro-hydroponic-fresh/index.html",
    "description": "Jadwal petik panen harian, jaminan sayur segar tanpa pestisida kimiawi, & langganan box sayur mingguan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "agro hydroponic fresh sayur hidroponik selada kangkung bebas pestisida panen",
    "badgeFeatures": []
  },
  {
    "id": "agro-orchard-fruit",
    "title": "Orchard Fruit Garden",
    "niche": "Orchard Fruit Garden",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group A",
    "folder": "agro-orchard-fruit",
    "demoUrl": "./05-agrobisnis-bahan-mentah/agro-orchard-fruit/index.html",
    "description": "Tingkat kematangan manis alami pohon, sistem pemesanan per kilo / karton, & pengiriman langsung ke konsumen.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "agro orchard fruit buah kebun mangga durian alpukat jeruk manis",
    "badgeFeatures": []
  },
  {
    "id": "agro-organic-rice",
    "title": "Organic Rice Grain",
    "niche": "Organic Rice Grain",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group A",
    "folder": "agro-organic-rice",
    "demoUrl": "./05-agrobisnis-bahan-mentah/agro-organic-rice/index.html",
    "description": "Kualitas bulir beras pulen bersertifikat organik, beras merah & hitam diet, serta suplai karungan rumah tangga.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "agro organic rice beras organik mentik wangi pandan wangi merah hitam",
    "badgeFeatures": []
  },
  {
    "id": "agro-mushroom-farm",
    "title": "Mushroom Cultivation Farm",
    "niche": "Mushroom Cultivation Farm",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group A",
    "folder": "agro-mushroom-farm",
    "demoUrl": "./05-agrobisnis-bahan-mentah/agro-mushroom-farm/index.html",
    "description": "Budidaya jamur tiram higienis terkontrol, pasokan jamur segar resto, & paket media tanam bibit baglog.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "agro mushroom farm jamur tiram kuping kancing baglog bibit",
    "badgeFeatures": []
  },
  {
    "id": "poultry-fresh-egg-farm",
    "title": "Fresh Egg Poultry Farm",
    "niche": "Fresh Egg Poultry Farm",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group B",
    "folder": "poultry-fresh-egg-farm",
    "demoUrl": "./05-agrobisnis-bahan-mentah/poultry-fresh-egg-farm/index.html",
    "description": "Sortir harian mutu Grade A, formulasi pakan herbal alami kaya omega 3, & pemesanan tray rak telur.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "poultry fresh egg telur omega ayam petelur peternakan herbal",
    "badgeFeatures": []
  },
  {
    "id": "fishery-fresh-seafood-hub",
    "title": "Fishery Seafood Hub",
    "niche": "Fishery Seafood Hub",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group B",
    "folder": "fishery-fresh-seafood-hub",
    "demoUrl": "./05-agrobisnis-bahan-mentah/fishery-fresh-seafood-hub/index.html",
    "description": "Tangkapan kapal nelayan harian, rantai dingin es terjamin, & pasokan udang/ikan segar ke restoran.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "fishery seafood ikan laut udang cumi nelayan rantai dingin segar",
    "badgeFeatures": []
  },
  {
    "id": "livestock-fresh-meat-ranch",
    "title": "Livestock Ranch Meat",
    "niche": "Livestock Ranch Meat",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group B",
    "folder": "livestock-fresh-meat-ranch",
    "demoUrl": "./05-agrobisnis-bahan-mentah/livestock-fresh-meat-ranch/index.html",
    "description": "Peternakan sapi penggemukan pakan rumput alami, standar potong halal MUI, & pemesanan hewan qurban.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "livestock meat ranch sapi ternak kambing qurban daging halal",
    "badgeFeatures": []
  },
  {
    "id": "dairy-raw-milk-homestead",
    "title": "Dairy Milk Homestead",
    "niche": "Dairy Milk Homestead",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group B",
    "folder": "dairy-raw-milk-homestead",
    "demoUrl": "./05-agrobisnis-bahan-mentah/dairy-raw-milk-homestead/index.html",
    "description": "Susu murni perah sapi & kambing etawa harian, pasteurisasi higienis tanpa pengawet, & olahan yoghurt alami.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "dairy raw milk susu sapi murni perah kambing etawa yoghurt",
    "badgeFeatures": []
  },
  {
    "id": "plantation-coffee-tea-estate",
    "title": "Coffee & Tea Estate",
    "niche": "Coffee & Tea Estate",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group C",
    "folder": "plantation-coffee-tea-estate",
    "demoUrl": "./05-agrobisnis-bahan-mentah/plantation-coffee-tea-estate/index.html",
    "description": "Ketinggian pegunungan sejuk nusantara, profil proses olah biji & teh pucuk daun, serta supply curah B2B.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "plantation coffee tea estate kopi teh kebun pegunungan single origin",
    "badgeFeatures": []
  },
  {
    "id": "spices-nusantara-trading",
    "title": "Spices Nusantara Trading",
    "niche": "Spices Nusantara Trading",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group C",
    "folder": "spices-nusantara-trading",
    "demoUrl": "./05-agrobisnis-bahan-mentah/spices-nusantara-trading/index.html",
    "description": "Kekayaan rempah-rempah kering asli, kemurnian aroma standar ekspor, & pasokan partai besar industri jamu.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "spices rempah cengkeh kapulaga kayu manis pala ekspor nusantara",
    "badgeFeatures": []
  },
  {
    "id": "raw-honey-wild-apiary",
    "title": "Raw Honey Wild Apiary",
    "niche": "Raw Honey Wild Apiary",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group C",
    "folder": "raw-honey-wild-apiary",
    "demoUrl": "./05-agrobisnis-bahan-mentah/raw-honey-wild-apiary/index.html",
    "description": "Madu mentah murni tanpa pasteurisasi perusak enzim, panen lestari hutan liar, & uji kemurnian laboratorium.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "raw honey madu hutan murni lebah dorsata nektar randu liar",
    "badgeFeatures": []
  },
  {
    "id": "agro-nursery-organic-fertilizer",
    "title": "Nursery & Organic Fertilizer",
    "niche": "Nursery & Organic Fertilizer",
    "bidang": "05-agrobisnis-bahan-mentah",
    "group": "Group C",
    "folder": "agro-nursery-organic-fertilizer",
    "demoUrl": "./05-agrobisnis-bahan-mentah/agro-nursery-organic-fertilizer/index.html",
    "description": "Kompos organik kaya mikroba penyubur tanah, bibit tanaman buah okulasi unggul, & media tanam siap pakai.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "agro nursery pupuk organik kompos bibit pohon tanah subur bibit",
    "badgeFeatures": []
  },
  {
    "id": "packaging-corrugated-box-factory",
    "title": "Corrugated Box Factory",
    "niche": "Corrugated Box Factory",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group A",
    "folder": "packaging-corrugated-box-factory",
    "demoUrl": "./06-supplier-grosir-b2b/packaging-corrugated-box-factory/index.html",
    "description": "Kapasitas skala pabrik manufaktur, pilihan ketebalan flute (B/C/E), & form hitung custom cetak box.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "packaging corrugated box factory kardus karton box pabrik kemasan cetak",
    "badgeFeatures": []
  },
  {
    "id": "packaging-food-standing-pouch",
    "title": "Food Standing Pouch",
    "niche": "Food Standing Pouch",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group A",
    "folder": "packaging-food-standing-pouch",
    "demoUrl": "./06-supplier-grosir-b2b/packaging-food-standing-pouch/index.html",
    "description": "Spesifikasi food-grade barrier foil zipper, opsi printing rotogravure & digital printing full color.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "packaging food standing pouch kemasan snack aluminium foil zipper sablon",
    "badgeFeatures": []
  },
  {
    "id": "packaging-luxury-rigid-box",
    "title": "Luxury Rigid Box",
    "niche": "Luxury Rigid Box",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group A",
    "folder": "packaging-luxury-rigid-box",
    "demoUrl": "./06-supplier-grosir-b2b/packaging-luxury-rigid-box/index.html",
    "description": "Sentuhan magnetik mewah, finishing hotprint foil emas & emboss timbul untuk produk prestige & kado korporat.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "packaging luxury rigid box hardbox hampers magnetik foil emboss premium",
    "badgeFeatures": []
  },
  {
    "id": "packaging-eco-kraft-paperbag",
    "title": "Eco Kraft Paperbag",
    "niche": "Eco Kraft Paperbag",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group A",
    "folder": "packaging-eco-kraft-paperbag",
    "demoUrl": "./06-supplier-grosir-b2b/packaging-eco-kraft-paperbag/index.html",
    "description": "Bahan daur ulang kraft kokoh ramah bumi, custom sablon brand toko ritel, & minimum order kuantiti transparan.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "packaging eco kraft paperbag kantong kertas ramah lingkungan sablon logo",
    "badgeFeatures": []
  },
  {
    "id": "garment-corporate-uniform",
    "title": "Corporate Uniform Garment",
    "niche": "Corporate Uniform Garment",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group B",
    "folder": "garment-corporate-uniform",
    "demoUrl": "./06-supplier-grosir-b2b/garment-corporate-uniform/index.html",
    "description": "Pilihan bahan kain drill premium (Japan / American), bordir komputer presisi, & kalkulator tender instansi.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "garment corporate uniform seragam kemeja kantor pabrik drill bordir",
    "badgeFeatures": []
  },
  {
    "id": "garment-safety-wearpack-k3",
    "title": "Safety Wearpack K3",
    "niche": "Safety Wearpack K3",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group B",
    "folder": "garment-safety-wearpack-k3",
    "demoUrl": "./06-supplier-grosir-b2b/garment-safety-wearpack-k3/index.html",
    "description": "Standar keselamatan kerja K3 tambang/migas, scotlite reflektor 3M terang, & material anti-flame/statis.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "garment safety wearpack k3 tambang proyek scotlite tahan api industri",
    "badgeFeatures": []
  },
  {
    "id": "garment-promo-apparel-screenprint",
    "title": "Promo Apparel & Screenprint",
    "niche": "Promo Apparel & Screenprint",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group B",
    "folder": "garment-promo-apparel-screenprint",
    "demoUrl": "./06-supplier-grosir-b2b/garment-promo-apparel-screenprint/index.html",
    "description": "Bahan katun combed 24s/30s adem, sablon plastisol/discharge awet, & pembuatan seragam event/merchandise.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "garment promo apparel screenprint kaos sablon combed hoodie merchandise event",
    "badgeFeatures": []
  },
  {
    "id": "textile-wholesale-fabric-rolls",
    "title": "Wholesale Fabric Rolls",
    "niche": "Wholesale Fabric Rolls",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group B",
    "folder": "textile-wholesale-fabric-rolls",
    "demoUrl": "./06-supplier-grosir-b2b/textile-wholesale-fabric-rolls/index.html",
    "description": "Pasokan gulungan kain langsung dari pabrik tenun, variasi gramasi katun/rayon/polyester, & katalog swatch fisik.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "textile wholesale fabric rolls kain gulungan rayon katun polyester grosir",
    "badgeFeatures": []
  },
  {
    "id": "wholesale-sembako-commodity-hub",
    "title": "Sembako Commodity Hub",
    "niche": "Sembako Commodity Hub",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group C",
    "folder": "wholesale-sembako-commodity-hub",
    "demoUrl": "./06-supplier-grosir-b2b/wholesale-sembako-commodity-hub/index.html",
    "description": "Pasokan tonase komoditas bahan pokok stabil, harga grosir harian real-time, & rute distribusi toko kelontong.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "wholesale sembako commodity hub beras minyak goreng gula tepung distributor",
    "badgeFeatures": []
  },
  {
    "id": "food-ingredients-bakery-raw-materials",
    "title": "Bakery Raw Ingredients",
    "niche": "Bakery Raw Ingredients",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group C",
    "folder": "food-ingredients-bakery-raw-materials",
    "demoUrl": "./06-supplier-grosir-b2b/food-ingredients-bakery-raw-materials/index.html",
    "description": "Bahan baku ragi instan, premiks kue, margarin industri & pasta perisa untuk kebutuhan pabrik roti/pastry.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "food ingredients bakery raw materials ragi margarin cokelat premiks tepung",
    "badgeFeatures": []
  },
  {
    "id": "chemical-industrial-cleaning-hygiene",
    "title": "Chemical & Hygiene Cleaning",
    "niche": "Chemical & Hygiene Cleaning",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group C",
    "folder": "chemical-industrial-cleaning-hygiene",
    "demoUrl": "./06-supplier-grosir-b2b/chemical-industrial-cleaning-hygiene/index.html",
    "description": "Konsentrat cairan pembersih industri, disinfektan rumah sakit & sertifikasi izin edar Kemenkes lengkap.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "chemical industrial cleaning hygiene sabun desinfektan kimia laundry pabrik",
    "badgeFeatures": []
  },
  {
    "id": "polymer-resin-plastic-pellets",
    "title": "Polymer & Plastic Pellets",
    "niche": "Polymer & Plastic Pellets",
    "bidang": "06-supplier-grosir-b2b",
    "group": "Group C",
    "folder": "polymer-resin-plastic-pellets",
    "demoUrl": "./06-supplier-grosir-b2b/polymer-resin-plastic-pellets/index.html",
    "description": "Grade virgin & daur ulang PP/HDPE/LDPE untuk proses injection & blowing molding manufaktur plastik.",
    "price": 149000,
    "originalPrice": 299000,
    "tags": "polymer resin plastic pellets biji plastik hdpe pp pe injection blow pabrik",
    "badgeFeatures": []
  }
];

// Expose globally for browser & node
if (typeof window !== 'undefined') {
  window.BIDANG_INFO = BIDANG_INFO;
  window.TEMPLATES_DATA = TEMPLATES_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BIDANG_INFO, TEMPLATES_DATA };
}
